language: go

env:
  - CODECOV_TOKEN="09c29d3f-46a3-4990-b797-da256bdc1c98"

go:
  - 1.12.x

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash) 
